#!/usr/bin/env bash
# Script installs nginx on the webserver that listens on port 80
# Get request using curl must return a page that contains the string
# Hello World!

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
