#!/usr/bin/env bash
# Script installs nginx on the webserver that listens on port 80
# Get request using curl must return a page that contains the string
# Hello World!
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo bash -c 'echo "server {
   listen 80;
   location / {
       echo "Hello World!";
   }
} > /etc/nginx/html/index.html'
sudo nginx -t
sudo service nginx start
