#!/usr/bin/env bash
#Install your load balancer

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Configure HAProxy for web-01 and web-02 with roundrobin algorithm
haproxy_cfg="/etc/haproxy/haproxy.cfg"

# Append our configuration
cat <<EOL | sudo tee -a $haproxy_cfg

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend webservers

backend webservers
    balance roundrobin
    server 200656-web-01 3.89.160.21:80 check
    server 200656-web-02 54.197.132.144:80 check

EOL

sudo systemctl restart haproxy
