#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100, Dispalys:
# FizzBuzz when no is mul of 3 and 5, Fizz when no is mul of 3
# Buzz when is mul of 5

for nm in {1..100}
do
	if ((nm % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((nm % 3 == 0))
	then
		echo "Fizz"
	elif ((nm % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$nm"
	fi
done
