#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10

n=1
while [ $n -le 10 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n+1))
done
