#!/usr/bin/env bash
# Script displays the time for 12 hours and 59 minutes:
#  display hours from 0 to 12
#  display minutes from 1 to 59

p=0
q=1

while [ $p -le 12 ]; do
	echo "Hour: $p"
	while [ $q -le 59 ]; do
		echo $q
		q=$((q+1))
	done
	q=$((1))
	p=$((i+1))
done
