#!/usr/bin/env bash
# Bash script that displays the content of the current directory
# In a list format where only part of name after 1st dash is displayed

for c in *; do
	echo "$c" | cut -d '-' -f 2
done
