#!/usr/bin/env bash
# ufw block all incomming trafic

sudo apt install ufw
sudo default deny incomming
sudo default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
