#!/usr/bin/env bash
#Run Nginx as Nginx

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions to read and write
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill  if running
pkill apache2
# start nginx service88 new nginx user
sudo -u nginx service nginx start
